---
- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted
  # in docker environment this handler would fail
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
