---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: ansible-fail2ban-noble
    box: cloud-image/ubuntu-24.04
  - name: ansible-fail2ban-jammy
    box: cloud-image/ubuntu-22.04
  - name: ansible-fail2ban-focal
    box: cloud-image/ubuntu-20.04
  - name: ansible-fail2ban-bookworm
    box: cloud-image/debian-12
    groups:
      - debian
  - name: ansible-fail2ban-bullseye
    box: cloud-image/debian-11
    groups:
      - debian

provisioner:
  name: ansible
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../shared/converge.yml
  inventory:
    group_vars:
      debian:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible
