---
dependency:
  name: galaxy

lint: |
  set -e
  yamllint . --strict
  ansible-lint

driver:
  name: docker

platforms:
  - name: instance
    image: docker.io/pycontribs/ubuntu
    pre_build_image: true

provisioner:
  name: ansible

verifier:
  name: ansible
