---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Should not miss package
      package:
        name: fail2ban
        state: present
      register: verify_package_install
      failed_when: verify_package_install.changed
